/*
 * generated by Xtext 2.35.0
 */
package org.gemoc.ql.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractQLScopeProvider extends DelegatingScopeProvider {
}
