/**
 * generated by Xtext 2.31.0
 */
package org.gemoc.qls.qLS.impl;

import org.eclipse.emf.ecore.EClass;

import org.gemoc.qls.qLS.NumericSpinnerStyle;
import org.gemoc.qls.qLS.QLSPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Numeric Spinner Style</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class NumericSpinnerStyleImpl extends NumericTypeSpinnerStyleImpl implements NumericSpinnerStyle
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected NumericSpinnerStyleImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QLSPackage.Literals.NUMERIC_SPINNER_STYLE;
  }

} //NumericSpinnerStyleImpl
