/**
 * generated by Xtext 2.31.0
 */
package org.gemoc.qls.qLS.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.gemoc.qls.qLS.Import;
import org.gemoc.qls.qLS.QLSModel;
import org.gemoc.qls.qLS.QLSPackage;
import org.gemoc.qls.qLS.QuestionStyle;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.gemoc.qls.qLS.impl.QLSModelImpl#getImports <em>Imports</em>}</li>
 *   <li>{@link org.gemoc.qls.qLS.impl.QLSModelImpl#getQuestionStyles <em>Question Styles</em>}</li>
 * </ul>
 *
 * @generated
 */
public class QLSModelImpl extends MinimalEObjectImpl.Container implements QLSModel
{
  /**
   * The cached value of the '{@link #getImports() <em>Imports</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getImports()
   * @generated
   * @ordered
   */
  protected EList<Import> imports;

  /**
   * The cached value of the '{@link #getQuestionStyles() <em>Question Styles</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getQuestionStyles()
   * @generated
   * @ordered
   */
  protected EList<QuestionStyle> questionStyles;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected QLSModelImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QLSPackage.Literals.QLS_MODEL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Import> getImports()
  {
    if (imports == null)
    {
      imports = new EObjectContainmentEList<Import>(Import.class, this, QLSPackage.QLS_MODEL__IMPORTS);
    }
    return imports;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<QuestionStyle> getQuestionStyles()
  {
    if (questionStyles == null)
    {
      questionStyles = new EObjectContainmentEList<QuestionStyle>(QuestionStyle.class, this, QLSPackage.QLS_MODEL__QUESTION_STYLES);
    }
    return questionStyles;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case QLSPackage.QLS_MODEL__IMPORTS:
        return ((InternalEList<?>)getImports()).basicRemove(otherEnd, msgs);
      case QLSPackage.QLS_MODEL__QUESTION_STYLES:
        return ((InternalEList<?>)getQuestionStyles()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case QLSPackage.QLS_MODEL__IMPORTS:
        return getImports();
      case QLSPackage.QLS_MODEL__QUESTION_STYLES:
        return getQuestionStyles();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case QLSPackage.QLS_MODEL__IMPORTS:
        getImports().clear();
        getImports().addAll((Collection<? extends Import>)newValue);
        return;
      case QLSPackage.QLS_MODEL__QUESTION_STYLES:
        getQuestionStyles().clear();
        getQuestionStyles().addAll((Collection<? extends QuestionStyle>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case QLSPackage.QLS_MODEL__IMPORTS:
        getImports().clear();
        return;
      case QLSPackage.QLS_MODEL__QUESTION_STYLES:
        getQuestionStyles().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case QLSPackage.QLS_MODEL__IMPORTS:
        return imports != null && !imports.isEmpty();
      case QLSPackage.QLS_MODEL__QUESTION_STYLES:
        return questionStyles != null && !questionStyles.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //QLSModelImpl
