/*
 * generated by Xtext 2.31.0
 */
package org.gemoc.qls.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class QLSUiModule extends AbstractQLSUiModule {

	public QLSUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
