<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ql" nsURI="http://www.gemoc.org/ql" nsPrefix="ql">
  <eClassifiers xsi:type="ecore:EClass" name="QLModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="forms" upperBound="-1"
        eType="#//Form" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="definitionGroup" upperBound="-1"
        eType="#//DefinitionGroup" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="canSubmit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="aspect"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="submitDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eAnnotations source="aspect"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Form" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="questionGroup" lowerBound="1"
        eType="#//QuestionGroup" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QuestionDefinition" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataType" lowerBound="1"
        eType="#//ValueType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="computedExpression" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentValue" eType="#//Value"
        containment="true">
      <eAnnotations source="aspect"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDisplayed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="aspect"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMandatory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultType" eType="#//ValueType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryExpression" abstract="true" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhsOperand" lowerBound="1"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhsOperand" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnaryExpression" abstract="true" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operand" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasicBinaryExpression" eSuperTypes="#//BinaryExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
        eType="#//BinaryOperatorKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BinaryOperatorKind">
    <eLiterals name="PLUS"/>
    <eLiterals name="MINUS" value="1"/>
    <eLiterals name="MULT" value="2"/>
    <eLiterals name="DIV" value="3"/>
    <eLiterals name="EQUAL" value="4"/>
    <eLiterals name="NOTEQUAL" value="5"/>
    <eLiterals name="GREATER" value="6"/>
    <eLiterals name="LOWER" value="7"/>
    <eLiterals name="GREATEROREQUAL" value="8"/>
    <eLiterals name="LOWEROREQUAL" value="9"/>
    <eLiterals name="AND" value="10"/>
    <eLiterals name="OR" value="11"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Call" abstract="true" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConstantCall" eSuperTypes="#//Call">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Value"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Value" abstract="true">
    <eAnnotations source="aspect"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerValue" eSuperTypes="#//Value">
    <eAnnotations source="aspect"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="intValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringValue" eSuperTypes="#//Value">
    <eAnnotations source="aspect"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stringValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanValue" eSuperTypes="#//Value">
    <eAnnotations source="aspect"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="booleanValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasicUnaryExpression" eSuperTypes="#//UnaryExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//UnaryOperatorKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UnaryOperatorKind">
    <eLiterals name="UNARYMINUS"/>
    <eLiterals name="NOT" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DateValue" eSuperTypes="#//Value">
    <eAnnotations source="aspect"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DecimalValue" eSuperTypes="#//Value">
    <eAnnotations source="aspect"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="decimalValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueType" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanValueType" eSuperTypes="#//ValueType"/>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerValueType" eSuperTypes="#//ValueType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DecimalValueType" eSuperTypes="#//ValueType"/>
  <eClassifiers xsi:type="ecore:EClass" name="DateValueType" eSuperTypes="#//ValueType"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnumerationValueType" eSuperTypes="#//ValueType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumerationLiterals" upperBound="-1"
        eType="#//EnumerationLiteral" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumerationLiteral">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionnalElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="guard" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QuestionGroup" eSuperTypes="#//ConditionnalElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="questionGroups" upperBound="-1"
        eType="#//QuestionGroup" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="questions" upperBound="-1"
        eType="#//Question" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DefinitionGroup">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataTypes" upperBound="-1"
        eType="#//ValueType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="questionDefinitions" upperBound="-1"
        eType="#//QuestionDefinition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QuestionCall" eSuperTypes="#//Call">
    <eStructuralFeatures xsi:type="ecore:EReference" name="question" lowerBound="1"
        eType="#//QuestionDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumerationCall" eSuperTypes="#//Call #//Value">
    <eAnnotations source="aspect"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumerationLiteral" lowerBound="1"
        eType="#//EnumerationLiteral"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringValueType" eSuperTypes="#//ValueType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Question">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Question represents the application of a QuestionDefinition in a given form"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="questionDefinition" lowerBound="1"
        eType="#//QuestionDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thenExpression" lowerBound="1"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseExpression" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
