/**
 * generated by Xtext 2.31.0
 */
package org.gemoc.qls.qLS;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Label Style</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.gemoc.qls.qLS.LabelStyle#isItalic <em>Italic</em>}</li>
 *   <li>{@link org.gemoc.qls.qLS.LabelStyle#isBold <em>Bold</em>}</li>
 * </ul>
 *
 * @see org.gemoc.qls.qLS.QLSPackage#getLabelStyle()
 * @model
 * @generated
 */
public interface LabelStyle extends EObject
{
  /**
   * Returns the value of the '<em><b>Italic</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Italic</em>' attribute.
   * @see #setItalic(boolean)
   * @see org.gemoc.qls.qLS.QLSPackage#getLabelStyle_Italic()
   * @model
   * @generated
   */
  boolean isItalic();

  /**
   * Sets the value of the '{@link org.gemoc.qls.qLS.LabelStyle#isItalic <em>Italic</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Italic</em>' attribute.
   * @see #isItalic()
   * @generated
   */
  void setItalic(boolean value);

  /**
   * Returns the value of the '<em><b>Bold</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bold</em>' attribute.
   * @see #setBold(boolean)
   * @see org.gemoc.qls.qLS.QLSPackage#getLabelStyle_Bold()
   * @model
   * @generated
   */
  boolean isBold();

  /**
   * Sets the value of the '{@link org.gemoc.qls.qLS.LabelStyle#isBold <em>Bold</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bold</em>' attribute.
   * @see #isBold()
   * @generated
   */
  void setBold(boolean value);

} // LabelStyle
