/**
 * generated by Xtext 2.31.0
 */
package org.gemoc.qls.qLS;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Numeric Type Style</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.gemoc.qls.qLS.QLSPackage#getNumericTypeStyle()
 * @model
 * @generated
 */
public interface NumericTypeStyle extends TypeStyle
{
} // NumericTypeStyle
