/**
 * generated by Xtext 2.31.0
 */
package org.gemoc.qls.qLS;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type Style</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.gemoc.qls.qLS.QLSPackage#getTypeStyle()
 * @model
 * @generated
 */
public interface TypeStyle extends EObject
{
} // TypeStyle
