/*
 * generated by Xtext 2.31.0
 */
package org.gemoc.qls;

import org.eclipse.xtext.scoping.IGlobalScopeProvider;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;
import org.eclipse.xtext.scoping.impl.ImportedNamespaceAwareLocalScopeProvider;
import org.gemoc.qls.scoping.QLSGlobalScopeProvider;

import com.google.inject.Binder;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class QLSRuntimeModule extends AbstractQLSRuntimeModule {

	@Override
	public void configure(Binder binder) {
		super.configure(binder);
		binder.bind(org.eclipse.xtext.scoping.IScopeProvider.class)
				.annotatedWith(com.google.inject.name.Names.named(AbstractDeclarativeScopeProvider.NAMED_DELEGATE))
				.to(ImportedNamespaceAwareLocalScopeProvider.class);
	}
	
	// support importURI global scoping
	public Class<? extends IGlobalScopeProvider> bindIGlobalScopeProvider() {
		return QLSGlobalScopeProvider.class;
	}
	
}
