/*
 * generated by Xtext 2.31.0
 */
package org.gemoc.qls.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class QLSAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/gemoc/qls/parser/antlr/internal/InternalQLS.tokens");
	}
}
