/**
 * generated by Xtext 2.31.0
 */
package org.gemoc.qls.scoping;

import com.google.common.base.Objects;
import com.google.inject.Inject;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IGlobalScopeProvider;
import org.eclipse.xtext.scoping.IScope;
import org.gemoc.qls.model.qls.QlsPackage;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class QLSScopeProvider extends AbstractQLSScopeProvider {
  @Inject
  private IGlobalScopeProvider globalScopeProvider;

  @Override
  public IScope getScope(final EObject context, final EReference reference) {
    boolean _matched = false;
    if (Objects.equal(reference, QlsPackage.Literals.QUESTION_STYLE__STYLED_QUESTION)) {
      _matched=true;
      return super.getScope(context, reference);
    }
    return super.getScope(context, reference);
  }
}
