/*
 * generated by Xtext 2.35.0
 */
package org.gemoc.ql;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class QLStandaloneSetup extends QLStandaloneSetupGenerated {

	public static void doSetup() {
		new QLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
