<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="qls" nsURI="http://www.gemoc.org/qls" nsPrefix="qls">
  <eClassifiers xsi:type="ecore:EClass" name="QLSModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="#//Import" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="questionStyles" upperBound="-1"
        eType="#//QuestionStyle" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="styledQLModel" lowerBound="1"
        eType="ecore:EClass ../../org.gemoc.ql.model/model/ql.ecore#//QLModel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Import">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeStyle"/>
  <eClassifiers xsi:type="ecore:EClass" name="NumericTypeStyle" eSuperTypes="#//TypeStyle"/>
  <eClassifiers xsi:type="ecore:EClass" name="QuestionStyle">
    <eStructuralFeatures xsi:type="ecore:EReference" name="styledQuestion" eType="ecore:EClass ../../org.gemoc.ql.model/model/ql.ecore#//QuestionDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="labelStyle" eType="#//LabelStyle"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeStyle" eType="#//TypeStyle"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LabelStyle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="italic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bold" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanTypeStyle" eSuperTypes="#//TypeStyle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="booleanStyleKind" eType="#//BooleanStyleKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumericTypeTextFieldStyle" eSuperTypes="#//NumericTypeStyle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="step" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumericTypeSpinnerStyle" eSuperTypes="#//NumericTypeStyle"/>
  <eClassifiers xsi:type="ecore:EClass" name="TextTypeStyle" eSuperTypes="#//TypeStyle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiline" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BooleanStyleKind">
    <eLiterals name="CHECKBOX" literal="CHECKBOX"/>
    <eLiterals name="TWO_RADIO" value="1" literal="TWO_RADIO"/>
    <eLiterals name="DROPDOWN" value="2" literal="DROPDOWN"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumericSpinnerStyle" eSuperTypes="#//NumericTypeSpinnerStyle"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnumerationTypeStyle" eSuperTypes="#//TypeStyle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enumerationStyleKing" lowerBound="1"
        eType="#//EnumerationStyleKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DateTypeStyle" eSuperTypes="#//TypeStyle"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EnumerationStyleKind">
    <eLiterals name="DROPDOWN"/>
    <eLiterals name="RADIO" value="1"/>
  </eClassifiers>
</ecore:EPackage>
