/**
 * generated by Xtext 2.35.0
 */
package org.gemoc.ql.formatting2;

import com.google.inject.Inject;
import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.formatting2.IHiddenRegionFormatter;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;
import org.eclipse.xtext.xbase.lib.Procedures.Procedure1;
import org.gemoc.ql.model.ql.DefinitionGroup;
import org.gemoc.ql.model.ql.QLModel;
import org.gemoc.ql.model.ql.Question;
import org.gemoc.ql.model.ql.QuestionDefinition;
import org.gemoc.ql.model.ql.QuestionGroup;
import org.gemoc.ql.model.ql.ValueType;
import org.gemoc.ql.services.QLGrammarAccess;

@SuppressWarnings("all")
public class QLFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private QLGrammarAccess _qLGrammarAccess;

  protected void _format(final QLModel qLModel, @Extension final IFormattableDocument document) {
    EList<QuestionGroup> _questionGroups = qLModel.getQuestionGroups();
    for (final QuestionGroup questionGroup : _questionGroups) {
      {
        final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
          it.indent();
        };
        document.<QuestionGroup>surround(questionGroup, _function);
        document.<QuestionGroup>format(questionGroup);
        final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
          it.noSpace();
        };
        document.<QuestionGroup>append(questionGroup, _function_1);
      }
    }
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.<QuestionGroup>append(IteratorExtensions.<QuestionGroup>last(qLModel.getQuestionGroups().iterator()), _function);
    final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
      it.setNewLines(1, 1, 2);
    };
    document.<QLModel>append(qLModel, _function_1);
    EList<DefinitionGroup> _definitionGroup = qLModel.getDefinitionGroup();
    for (final DefinitionGroup definitionGroup : _definitionGroup) {
      {
        final Procedure1<IHiddenRegionFormatter> _function_2 = (IHiddenRegionFormatter it) -> {
          it.indent();
        };
        document.<DefinitionGroup>surround(definitionGroup, _function_2);
        document.<DefinitionGroup>format(definitionGroup);
        final Procedure1<IHiddenRegionFormatter> _function_3 = (IHiddenRegionFormatter it) -> {
          it.noSpace();
        };
        document.<DefinitionGroup>append(definitionGroup, _function_3);
      }
    }
    final Procedure1<IHiddenRegionFormatter> _function_2 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.<DefinitionGroup>append(IteratorExtensions.<DefinitionGroup>last(qLModel.getDefinitionGroup().iterator()), _function_2);
  }

  protected void _format(final QuestionGroup questionGroup, @Extension final IFormattableDocument document) {
    EList<QuestionGroup> _questionGroups = questionGroup.getQuestionGroups();
    for (final QuestionGroup subGroup : _questionGroups) {
      {
        final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
          it.newLine();
        };
        document.<QuestionGroup>prepend(subGroup, _function);
        final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
          it.indent();
        };
        document.<QuestionGroup>surround(subGroup, _function_1);
        document.<QuestionGroup>format(subGroup);
        final Procedure1<IHiddenRegionFormatter> _function_2 = (IHiddenRegionFormatter it) -> {
          it.noSpace();
        };
        document.<QuestionGroup>append(subGroup, _function_2);
      }
    }
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.<QuestionGroup>append(IteratorExtensions.<QuestionGroup>last(questionGroup.getQuestionGroups().iterator()), _function);
    EList<Question> _questions = questionGroup.getQuestions();
    for (final Question question : _questions) {
      {
        final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
          it.newLine();
        };
        document.<Question>prepend(question, _function_1);
        final Procedure1<IHiddenRegionFormatter> _function_2 = (IHiddenRegionFormatter it) -> {
          it.indent();
        };
        document.<Question>surround(question, _function_2);
        document.<Question>format(question);
        final Procedure1<IHiddenRegionFormatter> _function_3 = (IHiddenRegionFormatter it) -> {
          it.noSpace();
        };
        document.<Question>append(question, _function_3);
      }
    }
    final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.<QuestionGroup>append(IteratorExtensions.<QuestionGroup>last(questionGroup.getQuestionGroups().iterator()), _function_1);
  }

  protected void _format(final DefinitionGroup definitionGroup, @Extension final IFormattableDocument document) {
    EList<QuestionDefinition> _questionDefinitions = definitionGroup.getQuestionDefinitions();
    for (final QuestionDefinition questionDefinition : _questionDefinitions) {
      {
        final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
          it.newLine();
        };
        document.<QuestionDefinition>prepend(questionDefinition, _function);
        final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
          it.indent();
        };
        document.<QuestionDefinition>surround(questionDefinition, _function_1);
        document.<QuestionDefinition>format(questionDefinition);
        final Procedure1<IHiddenRegionFormatter> _function_2 = (IHiddenRegionFormatter it) -> {
          it.noSpace();
        };
        document.<QuestionDefinition>append(questionDefinition, _function_2);
      }
    }
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.<QuestionDefinition>append(IteratorExtensions.<QuestionDefinition>last(definitionGroup.getQuestionDefinitions().iterator()), _function);
    final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
      it.setNewLines(1, 1, 2);
    };
    document.prepend(this.textRegionExtensions.regionFor(definitionGroup).keyword("definitions"), _function_1);
    EList<ValueType> _dataTypes = definitionGroup.getDataTypes();
    for (final ValueType dataType : _dataTypes) {
      {
        final Procedure1<IHiddenRegionFormatter> _function_2 = (IHiddenRegionFormatter it) -> {
          it.newLine();
        };
        document.<ValueType>prepend(dataType, _function_2);
        final Procedure1<IHiddenRegionFormatter> _function_3 = (IHiddenRegionFormatter it) -> {
          it.indent();
        };
        document.<ValueType>surround(dataType, _function_3);
        document.<ValueType>format(dataType);
        final Procedure1<IHiddenRegionFormatter> _function_4 = (IHiddenRegionFormatter it) -> {
          it.noSpace();
        };
        document.<ValueType>append(dataType, _function_4);
      }
    }
    final Procedure1<IHiddenRegionFormatter> _function_2 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.<QuestionDefinition>append(IteratorExtensions.<QuestionDefinition>last(definitionGroup.getQuestionDefinitions().iterator()), _function_2);
  }

  public void format(final Object qLModel, final IFormattableDocument document) {
    if (qLModel instanceof XtextResource) {
      _format((XtextResource)qLModel, document);
      return;
    } else if (qLModel instanceof QLModel) {
      _format((QLModel)qLModel, document);
      return;
    } else if (qLModel instanceof QuestionGroup) {
      _format((QuestionGroup)qLModel, document);
      return;
    } else if (qLModel instanceof DefinitionGroup) {
      _format((DefinitionGroup)qLModel, document);
      return;
    } else if (qLModel instanceof EObject) {
      _format((EObject)qLModel, document);
      return;
    } else if (qLModel == null) {
      _format((Void)null, document);
      return;
    } else if (qLModel != null) {
      _format(qLModel, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(qLModel, document).toString());
    }
  }
}
