/**
 */
package org.gemoc.qls.model.qls.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import org.gemoc.qls.model.qls.util.QlsAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class QlsItemProviderAdapterFactory extends QlsAdapterFactory
		implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public QlsItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.gemoc.qls.model.qls.QLSModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected QLSModelItemProvider qlsModelItemProvider;

	/**
	 * This creates an adapter for a {@link org.gemoc.qls.model.qls.QLSModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createQLSModelAdapter() {
		if (qlsModelItemProvider == null) {
			qlsModelItemProvider = new QLSModelItemProvider(this);
		}

		return qlsModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.gemoc.qls.model.qls.Import} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ImportItemProvider importItemProvider;

	/**
	 * This creates an adapter for a {@link org.gemoc.qls.model.qls.Import}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createImportAdapter() {
		if (importItemProvider == null) {
			importItemProvider = new ImportItemProvider(this);
		}

		return importItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.gemoc.qls.model.qls.TypeStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TypeStyleItemProvider typeStyleItemProvider;

	/**
	 * This creates an adapter for a {@link org.gemoc.qls.model.qls.TypeStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTypeStyleAdapter() {
		if (typeStyleItemProvider == null) {
			typeStyleItemProvider = new TypeStyleItemProvider(this);
		}

		return typeStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.gemoc.qls.model.qls.NumericTypeStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NumericTypeStyleItemProvider numericTypeStyleItemProvider;

	/**
	 * This creates an adapter for a {@link org.gemoc.qls.model.qls.NumericTypeStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNumericTypeStyleAdapter() {
		if (numericTypeStyleItemProvider == null) {
			numericTypeStyleItemProvider = new NumericTypeStyleItemProvider(this);
		}

		return numericTypeStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.gemoc.qls.model.qls.QuestionStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected QuestionStyleItemProvider questionStyleItemProvider;

	/**
	 * This creates an adapter for a {@link org.gemoc.qls.model.qls.QuestionStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createQuestionStyleAdapter() {
		if (questionStyleItemProvider == null) {
			questionStyleItemProvider = new QuestionStyleItemProvider(this);
		}

		return questionStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.gemoc.qls.model.qls.LabelStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LabelStyleItemProvider labelStyleItemProvider;

	/**
	 * This creates an adapter for a {@link org.gemoc.qls.model.qls.LabelStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLabelStyleAdapter() {
		if (labelStyleItemProvider == null) {
			labelStyleItemProvider = new LabelStyleItemProvider(this);
		}

		return labelStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.gemoc.qls.model.qls.BooleanTypeStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BooleanTypeStyleItemProvider booleanTypeStyleItemProvider;

	/**
	 * This creates an adapter for a {@link org.gemoc.qls.model.qls.BooleanTypeStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBooleanTypeStyleAdapter() {
		if (booleanTypeStyleItemProvider == null) {
			booleanTypeStyleItemProvider = new BooleanTypeStyleItemProvider(this);
		}

		return booleanTypeStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.gemoc.qls.model.qls.NumericTypeTextFieldStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NumericTypeTextFieldStyleItemProvider numericTypeTextFieldStyleItemProvider;

	/**
	 * This creates an adapter for a {@link org.gemoc.qls.model.qls.NumericTypeTextFieldStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNumericTypeTextFieldStyleAdapter() {
		if (numericTypeTextFieldStyleItemProvider == null) {
			numericTypeTextFieldStyleItemProvider = new NumericTypeTextFieldStyleItemProvider(this);
		}

		return numericTypeTextFieldStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.gemoc.qls.model.qls.NumericTypeSpinnerStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NumericTypeSpinnerStyleItemProvider numericTypeSpinnerStyleItemProvider;

	/**
	 * This creates an adapter for a {@link org.gemoc.qls.model.qls.NumericTypeSpinnerStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNumericTypeSpinnerStyleAdapter() {
		if (numericTypeSpinnerStyleItemProvider == null) {
			numericTypeSpinnerStyleItemProvider = new NumericTypeSpinnerStyleItemProvider(this);
		}

		return numericTypeSpinnerStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.gemoc.qls.model.qls.TextTypeStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TextTypeStyleItemProvider textTypeStyleItemProvider;

	/**
	 * This creates an adapter for a {@link org.gemoc.qls.model.qls.TextTypeStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTextTypeStyleAdapter() {
		if (textTypeStyleItemProvider == null) {
			textTypeStyleItemProvider = new TextTypeStyleItemProvider(this);
		}

		return textTypeStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.gemoc.qls.model.qls.EnumerationTypeStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnumerationTypeStyleItemProvider enumerationTypeStyleItemProvider;

	/**
	 * This creates an adapter for a {@link org.gemoc.qls.model.qls.EnumerationTypeStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEnumerationTypeStyleAdapter() {
		if (enumerationTypeStyleItemProvider == null) {
			enumerationTypeStyleItemProvider = new EnumerationTypeStyleItemProvider(this);
		}

		return enumerationTypeStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.gemoc.qls.model.qls.DateTypeStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DateTypeStyleItemProvider dateTypeStyleItemProvider;

	/**
	 * This creates an adapter for a {@link org.gemoc.qls.model.qls.DateTypeStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDateTypeStyleAdapter() {
		if (dateTypeStyleItemProvider == null) {
			dateTypeStyleItemProvider = new DateTypeStyleItemProvider(this);
		}

		return dateTypeStyleItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>) type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (qlsModelItemProvider != null)
			qlsModelItemProvider.dispose();
		if (importItemProvider != null)
			importItemProvider.dispose();
		if (typeStyleItemProvider != null)
			typeStyleItemProvider.dispose();
		if (numericTypeStyleItemProvider != null)
			numericTypeStyleItemProvider.dispose();
		if (questionStyleItemProvider != null)
			questionStyleItemProvider.dispose();
		if (labelStyleItemProvider != null)
			labelStyleItemProvider.dispose();
		if (booleanTypeStyleItemProvider != null)
			booleanTypeStyleItemProvider.dispose();
		if (numericTypeTextFieldStyleItemProvider != null)
			numericTypeTextFieldStyleItemProvider.dispose();
		if (numericTypeSpinnerStyleItemProvider != null)
			numericTypeSpinnerStyleItemProvider.dispose();
		if (textTypeStyleItemProvider != null)
			textTypeStyleItemProvider.dispose();
		if (enumerationTypeStyleItemProvider != null)
			enumerationTypeStyleItemProvider.dispose();
		if (dateTypeStyleItemProvider != null)
			dateTypeStyleItemProvider.dispose();
	}

}
