/*
 * generated by Xtext 2.31.0
 */
package org.gemoc.qls.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.gemoc.ql.validation.QLValidator;

public abstract class AbstractQLSValidator extends QLValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>(super.getEPackages());
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.gemoc.org/qls"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.gemoc.org/ql"));
		return result;
	}
}
