/**
 * generated by Xtext 2.31.0
 */
package org.gemoc.qls.tests;

import com.google.inject.Inject;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.gemoc.qls.model.qls.QLSModel;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(InjectionExtension.class)
@InjectWith(QLSInjectorProvider.class)
@SuppressWarnings("all")
public class QLSParsingTest {
  @Inject
  private ParseHelper<QLSModel> parseHelper;

  @Test
  public void loadModel() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("import \"challengeHouseOwningQuestionnaire.ql\"");
      _builder.newLine();
      _builder.newLine();
      _builder.append("QLSModel { ");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("questionStyles { ");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("styledQuestion HouseOwning.hasBoughtHouse {labelStyle { bold }}");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("styledQuestion HouseOwning.valueResidue { labelStyle {italic}}");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      final QLSModel result = this.parseHelper.parse(_builder);
      Assertions.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      boolean _isEmpty = errors.isEmpty();
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("Unexpected errors: ");
      String _join = IterableExtensions.join(errors, ", ");
      _builder_1.append(_join);
      Assertions.assertTrue(_isEmpty, _builder_1.toString());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
