/*
 * generated by Xtext 2.31.0
 */
package org.gemoc.qls.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import org.gemoc.qls.model.qls.QLSModel

@ExtendWith(InjectionExtension)
@InjectWith(QLSInjectorProvider)
class QLSParsingTest {
	@Inject
	ParseHelper<QLSModel> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			import "challengeHouseOwningQuestionnaire.ql"
			
			QLSModel { 
				questionStyles { 
					styledQuestion HouseOwning.hasBoughtHouse {labelStyle { bold }}
					styledQuestion HouseOwning.valueResidue { labelStyle {italic}}
				}
			}
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
